### ISSUE TITLE
Java 8?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#1]
Considering this repository is scoped to backend components only, and has no ambition to share code with clients, should the base language level be Java 8?

**Comment by michaelsembwever** [comment]
+1

**Comment by jen20** [comment]
+1

**Comment by greggdonovan** [comment]
+1

**Comment by spencergibb** [comment]
:+1:

**Comment by rtyler** [comment]
IMHO this is a great idea, and makes it easy to use language features in Java 8 that make writing code much more enjoyable!

**Comment by rtyler** [comment]
See also [RxJava](https://github.com/ReactiveX/RxJava)

**Comment by adriancole** [comment]
java 8 for everything except "core" which brave might re-use as it needs the model objects. RxJava tracking in another issue #6 

closed via #5
