### ISSUE TITLE
Elasticsearch support

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin-java#103]
Any thoughts on supporting elasticsearch in zipkin-java? Elasticsearch is extremely easy to set up as a cluster in a reasonably scalable and high-performance manner, so I think it's a good fit with zipkin.

I noticed the zipkin-elasticsearch-scala repo which is empty, so if that hasn't started yet maybe going straight to Java makes sense.

I have implemented it in a fork here https://github.com/anuraaga/zipkin-java/pull/1 (integration tests pass, no dependency link support as I'm not yet sure what those are yet and the cassandra store doesn't seem to implement them). Let me know if this is something you're interested in merging in :) 

One concern may be the size of the elasticsearch dependency. I noticed #102 - do you think we'll make the dependencies optional and expect people to include the spanstore jar with -Ploader.path? I think this will work ok but haven't tried it yet.

https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-property-launcher-features

**Comment by eirslett** [comment]
Yes, we've discussed using elasticsearch as a backend, and I think doing it in Java is better than Scala. The dependency-link stuff is implemented as a spark analysis job (https://github.com/openzipkin/zipkin-dependencies-spark), it's way too expensive to compute the dependency graph on-the-fly. (It's done in the MySQL backend implementation, but that's not really meant for production usage)

**Comment by anuraaga** [comment]
Thanks - I think I can implement a similarly non-production worthy version for elasticsearch, but maybe it's better to just return an empty list or exception and possibly implement after adding it to the spark job? Let me know if that makes sense.

**Comment by eirslett** [comment]
We could use a heuristic. If there exists a "dependency" index in ES, and we get results from it, we could assume the spark job was run, and query against that. And if not, fallback to doing a direct query against the span index. (If you're able to perform it as an ES query, I'm not sure whether it will be too complex or not)
The latter case could run with a timeout of ~5 seconds; then it works for small environments, but probably not in production.

**Comment by adriancole** [comment]
Sounds good cc @jcarres-mdsol
