### ISSUE TITLE
zipkin-server modularity

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#108]
Currently, zipkin-server needs to know up-front which span stores or transports it can support. This was helpful during the early stages of development, as options were limited, dependencies weren't broad and we've never done modularity in zipkin-scala, yet. As noted in #107 we could do a bit more here, taking advantage of some spring-boot packaging options.

## Option 1: Isolate spring config and move zipkin-server's exec jar packaging from JAR to ZIP layout
One option presented by @anuraaga was to change the exec jar packaging from JAR to ZIP. ZIP uses the PropertiesLoader which is identical to JAR with no options, but also gives the option to add jars to the classpath, for example. It allows easily starting up the server with various plugins.

### Impact
To add a new span store, a jar that bundles spring configuration can be added to `LOADER_PATH`  at runtime. This allows the server to startup with various plugins. This is easy to document and understand from a user POV. ex. add this single file and corresponding configuration

### Work needed
We'd still need to package the spring configuration somewhere, and publish them. We can't forget that zipkin-server is not the only consumer of zipkin-java libraries.

#### Optional dependency of the component
For example, the spring configuration could be an optional dependency of the span stores themselves. We'd have to be careful to test that spring is in fact an optional dependency, as not all users of span stores will be running spring, or the same version of spring as zipkin-server is. For example, this might mean running a nested maven invoker. We may still need to publish a separate artifact, if we need an all-jar (for single-file plugin purposes)

#### Buddy component
Spring configuration could be in a separate maven dependency, which packages an all jar and includes tests that exercise the server. Ex. for spanstore-elasticsearch, the buddy could be spanstore-elasticsearch-plugin, or activator. This adds another explicit maven project, but simplifies and isolates the build/test/publish concern. It also can correctly couple the version of spring-boot to zipkin-server.

## Recap of status quo
Currently, zipkin-server has compile dependencies on all possible span stores and transports, but these are optional at runtime. Tricks like below are used to ensure those classes are indeed optional, and not asked for unless they are really needed.

```java
@ConditionalOnProperty(name = "zipkin.store.type", havingValue = "elasticsearch")
@ConditionalOnClass(name = "zipkin.elasticsearch.ElasticsearchSpanStore")
```
### Why are these optional
zipkin-server is a base component that you can derive other spring-boot applications from (via the `@EnableZipkinServer` annotation). For example, [spring-cloud-sleuth-zipkin-stream](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin-stream) extends zipkin to add a non-standard span transport. It only includes the JDBC span store, and not the Cassandra one.

### How we test things are optional
zipkin-server includes an [integration test](https://github.com/openzipkin/zipkin-java/blob/master/zipkin-server/src/it/minimal-dependencies/pom.xml) that does not import any of the optional dependencies. This test fails when a dependency leaks.

### If things are optional, how does the -exec jar work?
Those who look carefully will notice that the [zipkin-server](http://search.maven.org/#artifactdetails%7Cio.zipkin.java%7Czipkin-server%7C0.9.1%7Cjar) jar is hefty :) Ex it is 36megs. The current packaging bundles all optional dependencies into the exec jar, even if they are not hard dependencies on `zipkin-server`. This allows zipkin-server to be a drop-in replacement for the zipkin-scala jars, which also bundle all dependencies.

### Limitation to modularity
Similar to the zipkin-scala project, the current incarnation of zipkin-server needs to know up-front the span stores it can support. This has the same limitations.
* The exec jar is larger than necessary (currently 36MB)
* There's a chance of library conflicts between transports or span store components
* In order to add a new spanstore or transport, you need to do undocumented things beyond just implementing `SpanStore`, for example.
  * make a conditional configuration object
  * make an integration test that shows zipkin-server actually works when using this
  * somehow load the classes you need and get them to appear in docker somehow

**Comment by adriancole** [comment]
I did my best to capture the concern and the known options, please contribute!

cc @dsyer @marcingrzejszczak @abesto @anuraaga

**Comment by abesto** [comment]
I'm afraid I got a bit lost in all the juicy Java details; I have only a vague understanding of the involved components (mainly Spring and friends). Bit confused because of that: is this one proposed option (Isolate spring config and move zipkin-server's exec jar packaging from JAR to ZIP layout) with two work items ("Optional dependency of the component" and "Buddy component"), or two possible implementations of the option, or two slightly different options?

**Comment by adriancole** [comment]
The jist is consider moving the "plugins" to separate modules, so that we
end up with a single file like plugin-elasticsearch.jar that includes all
ElasticSearch's transitives plus configuration code to enable it in
zipkin-server. At the end of the day, dropping that file into a path and
adding a flag would enable it on the server.

Making sense?

**Comment by abesto** [comment]
Absolutely; to my mind, that would be ideal. I got a bit lost in the implementation details, but I fully support the goal.

**Comment by anuraaga** [comment]
FWIW, spring-boot's idiomatic packaging is indeed exactly the buddy component. For autoconfigured packages, there's usually a, e.g. spanstore-elasticsearch and spanstore-elasticsearch-autoconfigure module. For our use case, only the latter would have spring-boot dependencies.

I'm wondering, are we setting the scope as a system that allows third-parties to build their own plugins that will be automatically loaded, presumably with spring-boot AutoConfiguration? Or just a way to get our own packages to be loadable from outside the server jar? I think the difference isn't so big, other than removing the Store.Type enum as it wouldn't be a fixed value anymore

**Comment by adriancole** [comment]
I think the first goal is to split up the modules, and Store.Type should
go, as that hints at a central registry which isn't gonna last.

The way I see it, zipkin-server's exec jar ends up only setting up
in-memory span store on missing bean, but without using an enum.

If naming conventions and spring boot idioms say the optional things like
kafka, elasticsearch should be named autoconfiguration, I wouldn't argue
until we have reason to. There is some trickiness depending on how auto we
want to be.. For example, Kafka can coexist with other things, but span
stores are mutually exclusive.

**Comment by adriancole** [comment]
The autoconfigure route looks like it will work. There's some unwinding to do first.

For example, I'm debating whether to extract a module to hold the wrapper `ZipkinHealthIndicator`, or do some dynamic bean registration instead (ex trap `zipkin.Component`s, and register a ZipkinHealthIndicator bean dynamically)

**Comment by adriancole** [comment]
first cut at autoconfig https://github.com/openzipkin/zipkin-java/pull/236

**Comment by adriancole** [comment]
Next step is to look closely at packaging of the exec jar and see if we need/want to change it before 1.0

Right now, we use "optional dependencies" to make the exec jar include everything (kafka etc). I don't know how to do multiple ad-hoc layers in a docker project.. we probably need to decide how to treat 1.0

For example, do we make the exec jar still a big'n (as it is easy to reason with), but modify it to allow folks to add other things when in docker (ex put another layer here, which includes neo4j or some other storage)?

Or.. do we split it up (which means that someone downloading the jar can only use in-memory unless they download something else)? If we split it up, we'd need some way to put the common layers together in docker.. ex. mysql + kafka.

**Comment by anuraaga** [comment]
How about publish 3 jars?

1) No deps, for use as a library
2) Minimal deps, for use in-memory or with a plugin or two using LOADER_PATH
3) All deps, for easy running with any config at the expense of binary size

That should be reasonably easy to configure and satisfy all use cases, including docker (whether you go with some layering approach or just using the all-deps jar, somehow it should work out).

**Comment by adriancole** [comment]
excellent idea. what should we name the classifier for the one that uses
LOADER_PATH? minimal?

**Comment by anuraaga** [comment]
Some ideas

2 - minimal, pluggable, slim, simple
3 - full, allplugins, alldeps, fat, godzilla

To pick just one, I'd probably go with slim/full.

**Comment by adriancole** [comment]
I'm cool on slim/full

Right now, we'd have to opt-in in order to get even the UI. Should we add
the UI to slim? One reason not to is that you can more easily change the
UI, by using the filesystem, if we don't. Also, some folks don't cohost the
UI (ex they use nginx). Basically, we could start slim as really nothing
except the http endpoints.

**Comment by eirslett** [comment]
I suggest -minimal/-full for naming (minimal is more widely used/recognised in software lingo, I think?)

One thing we could do is to only support 1 and 3, with very good documentation on how to assemble your custom server - you shouldn't need maven or javac to do it, only drop the right jar files to the right folders, set up configuration and so on.

You get two options; either manual or automatic transmission. Running the fatjar as-is works like a charm, we do it in production.

The fewer alternatives we provide, the easier it will be for project committers to maintain the distributions, so that we can spend more energy on other tasks. We also avoid having to make decisions in grey-zone areas like "should the UI be included".

**Comment by adriancole** [comment]
good points.
