### ISSUE TITLE
Migrate to gradle?

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin-java#120]
Dealing with multiple modules in maven seems very annoying (especially keeping parent pom versions in sync).

My experience with gradle is that, it isn't ;)

Thoughts? If most team members are more comfortable with maven, no worries just wanted to check.

**Comment by eirslett** [comment]
This is a duplicate of #4.
The decision was made based on the state of zipkin-java at the time. I'm not sure anything has changed since then.

> especially keeping parent pom versions in sync

The maven release plugin is fortunately good at handling that automatically :smile:

**Comment by anuraaga** [comment]
Apologies for not searching, I should have known this would have come up already!

FWIW my main pain point was having to update the parent pom reference of a new module a few times during a PR, which is not a big deal but easy to forget (maybe Travis actually would check it though if so that's good :) )

I also found that I have to mvn install to make the parent pom available or mvn package doesn't work. This felt unnatural to me since the pom is in my dev workspace but maybe it's just my lack of maven-fu and there's a better way.

Anyways, no need for another issue on the same topic will close this.

**Comment by eirslett** [comment]
Yup. Maven (like most tools) definitely has its quirks ;-)
