### ISSUE TITLE
Elasticsearch Version

### ISSUE THREAD

**Issue by jlisam-insikt** [openzipkin/zipkin-java#123]
Hello,

So recently I wanted to test out elasticsearch (ES) as a storage type, and unfortunately our system is currently running 1.4.2 (server and client). The current ES version in zipkin-java is 2.2.1. I used this client to connect to the ES cluster but I kept getting an exception.

> Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{192.168.99.100}{dockerhost/192.168.99.100:9300}]]
> 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
> 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
> 	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
> 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:286)
> 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
> 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:340)
> 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1182)
> 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.getTemplates(AbstractClient.java:1617)
> 	at zipkin.elasticsearch.ElasticsearchSpanStore.checkForIndexTemplate(ElasticsearchSpanStore.java:383)
> 	at zipkin.elasticsearch.ElasticsearchSpanStore.<init>(ElasticsearchSpanStore.java:93)
> 	at zipkin.server.ZipkinServerConfiguration$ElasticsearchConfiguration.elasticsearchSpanStore(ZipkinServerConfiguration.java:153)
> 	at zipkin.server.ZipkinServerConfiguration$ElasticsearchConfiguration$$EnhancerBySpringCGLIB$$58be8e54.CGLIB$elasticsearchSpanStore$0(<generated>)
> 	at zipkin.server.ZipkinServerConfiguration$ElasticsearchConfiguration$$EnhancerBySpringCGLIB$$58be8e54$$FastClassBySpringCGLIB$$edafdfe6.invoke(<generated>)
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
> 	at zipkin.server.ZipkinServerConfiguration$ElasticsearchConfiguration$$EnhancerBySpringCGLIB$$58be8e54.elasticsearchSpanStore(<generated>)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

I am guessing it's because of the version? Any ideas?

**Comment by adriancole** [comment]
I'd be unsurprised if version was related, just on account of google
searching anyway. We should post a version range in the README as I'm not
sure the version policy of ES.

How big of a deal is it to host tracing data in a newer cluster? Is your
site planning to update any time soon?

**Comment by anuraaga** [comment]
FWIW Elasticsearch 2 is mentioned in the spanstore-elasticsearch README, but forgot to add the 2 on the top-level. IMO it's a bit too much for a new project like this one to support both versions of Elasticsearch since they're highly incompatible.

**Comment by adriancole** [comment]
Oh OK,  so there is no backwards compatibility of ES 2 to ES 1. Good to
know.

**Comment by adriancole** [comment]
closing because I agree that right now, we don't have resources to make a second implementation of ES
