### ISSUE TITLE
CharsetEncoder in CassandraUtil not threadsafe

### ISSUE THREAD

**Issue by nrogasch** [openzipkin/zipkin-java#125]
Hi guys,

I found that the Implementation of toByteBuffers() in zipkin.cassandra.CassandraUtil in the spanstore-cassandra project is not thread safe and leads to the occurence of the following errors:

 ERROR 26858 --- [skExecutor-9983] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void zipkin.server.ZipkinSpanWriter.accept(java.util.List)'.
java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
 at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:992) ~[na:1.8.0_72]
        at java.nio.charset.CharsetEncoder.flush(CharsetEncoder.java:675) ~[na:1.8.0_72]
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:804) ~[na:1.8.0_72]
        at zipkin.cassandra.CassandraUtil.toByteBuffers(CassandraUtil.java:87) ~[spanstore-cassandra-0.9.3.jar!/:na]

The reason for this is the static use of the CharsetEncoder (constant UTF8_ENCODER), since the CharsetEncoder is not designed threadsafe.

I wrapped the CharsetEncoder in a ThreadLocal to solve the issue and just wanted to let you know of this, cause I greatly appreciate this project but am not to familiar with the whole open source development techniques ;o)

Here's my solution to the problem, feel free to use it for a fix:
[CassandraUtil.java.txt](https://github.com/openzipkin/zipkin-java/files/188058/CassandraUtil.java.txt)

**Comment by adriancole** [comment]
thanks for the report! will fix
