### ISSUE TITLE
Elasticsearch request.limit doesn't work properly

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin-java#127]
After ingesting some millions of spans I've realized that the pipeline aggregation trick didn't work out for limiting traces as the limit is applied before the filtering happens. I guess this isn't so suprising, backtracking out of a filter to do ordering seemed to good to be true.

I'll try replacing it with two queries, one to get filtered traces, and one to order by unfiltered spans with the limit. Trying it out the performance doesn't seem like it'll be a problem. Admittedly RAM usage within zipkin-server will go up if lots of traces match the filtered query, but trying with ~100K matched traces, the queries each finish in a couple dozen milliseconds so maybe it's ok.

**Comment by anuraaga** [comment]
Of course, if we didn't have to order by first span but just any span, the problem goes away with possibly little user-visible effect since the difference between ordering on filtered spans and unfiltered spans probably only shows up in unit tests.

**Comment by adriancole** [comment]
The order of magnitude of lookback is days, and folks have asked to adjust it to hours.. I suspect that if there are variances of which span in the trace's timestamp we're looking at, the end user wouldn't know.

I don't know ES enough to tell what's the best idea, but my hunch is that pulling back even (traceid, timestamp) pairs to do client-side order/limit might blow up memory considering default lookback is 7 days I think. This is a trickly issue, and why there's a separate index like cassandra's service_name_index or the mutable zipkin_spans.start_ts in jdbc.

good luck and thanks for thinking this through!

**Comment by anuraaga** [comment]
>  the end user wouldn't know.

@adriancole To make sure I follow, by this are you suggesting that indeed, sorting on filtered spans would be a reasonable compromise? I'm leaning towards this myself as it should guarantee good performance.

**Comment by anuraaga** [comment]
By the way, here is the comment I would write to explain the behavior.

https://github.com/anuraaga/zipkin-java/blob/zipkin-armeria-server/zipkin-spanstores/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchSpanStore.java#L145

**Comment by adriancole** [comment]
The results are to be ordered by first (usually root) span, but that
shouldn't affect your server queries. Ex clock skew will screw that up
anyway, as would multiple copies of the same span (why we merge).
Basically, I'd treat the sorting of returned results as a client-side
concern, as usually only 10 are returned, and the chain of merge, clock
skew, etc ends up needing us to re-sort anyway.

All that in mind, try to split the task of filtering against endTs and
limit from the task of sorting the end results. I hope this helps!
