### ISSUE TITLE
Automatic sync to maven central

### ISSUE THREAD

**Issue by ewhauser** [openzipkin/zipkin-java#131]
Since we already upload releases to bintray, it appears straightforward to also have the releases copied over to central:

https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

**Comment by adriancole** [comment]
So, the current process is me or someone else doing this: ./mvnw -s
./.settings.xml release:prepare
then waiting for things, and if they didn't break, clicking through the
bintray maven central sync..

If there's a way to change the release plugin to automatically do the
bintray maven central sync, sounds good to me. Even better, if I don't have
to do the release:prepare from my laptop (because of some tag-driven flow)

**Comment by ewhauser** [comment]
Poked around a bit on this.  There is a gradle plugin for bintray that has the capability to upload to maven central, and here is the API it uses:

https://github.com/bintray/gradle-bintray-plugin/blob/a0e57d6ca6c586a321561b53843ed6f377441fd3/src/main/groovy/com/jfrog/bintray/gradle/BintrayUploadTask.groovy#L404

Seems like we could write a Maven plugin to do the same.

**Comment by adriancole** [comment]
hah.. looks like an easy fix.

https://github.com/bintray/bintray-examples/blob/master/maven-example/pom.xml#L52

**Comment by adriancole** [comment]
oops.. that was just to publish in to jcenter.. and we already have that :P

**Comment by abesto** [comment]
Created #155 to separately track the "release via tag" story.

**Comment by abesto** [comment]
Drafted a Maven plugin in https://github.com/openzipkin/zipkin-java/tree/maven-central-sync. TODOs include (but are not limited to) safely passing in username / password, and calling the task at the appropriate moment in the lifecycle (probably `deploy`, after the release task, probably configured from the name of each subproject in `pluginManagement`, but I haven't done this before)

**Comment by adriancole** [comment]
added setting reading to the plugin and buffed some things.. give it a try!

# should fail as it can't find the username and password

$  ./mvnw -Dcentralsync.dryRun=true
io.zipkin.java:centralsync-maven-plugin:sync

# should proceed as it can

$ ./mvnw -Dcentralsync.dryRun=true
io.zipkin.java:centralsync-maven-plugin:sync -s ./.settings.xml

**Comment by abesto** [comment]
After #163 and following work, plus #160, we're now a single integration away from making this happen.

**Comment by adriancole** [comment]
not quite there. the plugin was failing due to authentication problems which require a code change

**Comment by adriancole** [comment]
works now!
