### ISSUE TITLE
elasticsearch store getRawTrace return  only 10 spans

### ISSUE THREAD

**Issue by eisig** [openzipkin/zipkin-java#159]
When open span view screen, if the trace has more then 10 spans, it won't work. "getRawTrace" return  only 10 spans. 
The UI looks like  https://github.com/openzipkin/zipkin/issues/1085
Set the reuqest size to large size to make it work.

**Comment by adriancole** [comment]
can you be more specific about the problem. I'm not sure if you are reporting two issues or one. Are you seeing a UI error as well?

It seems you are saying that anything with more than 10 spans isn't returned.. is it truncated to 10? what do you mean by set request size to a large size? Do you mean in the code?

**Comment by adriancole** [comment]
will add a test for this now

**Comment by adriancole** [comment]
bug!
