### ISSUE TITLE
Make QueryRequest.serviceName nullable

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#182]
per https://github.com/openzipkin/zipkin/pull/1102, the zipkin http api query currently has no way to request traces across services, making it difficult to show any sort of inter-service overview ui.

proposed solution: change serviceName from being required to being optional. This means making `QueryRequest.serviceName` nullable, introducing tests, and updating the http api docs.

This might break some assumptions, or be expensive, depending on the storage component and what assumptions are baked in vs pliable.

Here's a checklist of storage components that work with this:

- [ ] mem
- [ ] mysql
- [ ] cassandra
- [ ] elasticsearch

**Comment by anuraaga** [comment]
This is trivial implementation-wise for elastic search, we guard the addition of servicename to the query just like other optional attributes like duration. Performance will go down a lot though as there will be more spans processed by the trace ID aggregation, I can try it out on a billion spans next week to see what this will feel like.
