### ISSUE TITLE
Change storage library artifactIds to include "zipkin"

### ISSUE THREAD

**Issue by dsyer** [openzipkin/zipkin-java#193]
It's not very likely, but it's quite possible that another library called "jdbc-storage" could clash with the zipkin one on the classpath because of the file name, for instance. In general though, I think it is a courtesy to users to use names for artifacts that can be identified when looking at the file itself, so the "zipkin-" prefix should be added to all jars.

**Comment by adriancole** [comment]
sounds fair. will do.

**Comment by adriancole** [comment]
will cut a release on green https://github.com/openzipkin/zipkin-java/pull/194
