### ISSUE TITLE
document easy path to getting zipkin-server's jar

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#198]
We don't have any doc saying just download this and java -jar it

https://jcenter.bintray.com/io/zipkin/java/zipkin-server/0.17.1/:zipkin-server-0.17.1-exec.jar

right now, people get the impression they need to run maven in order to run zipkin. If we had an alternative, folks who struggle with maven or just want the jar could have an easier time.

The trick will be to make this maintenance free.. ex. is there a way we can have a link to the most recent release ever-fresh?

cc @abesto

**Comment by eirslett** [comment]
We already have a "Download" badge in the README, but it's very easy to overlook. (case in point, even project maintainers overlook it)

**Comment by adriancole** [comment]
good point. although we still need to tell people what to download. ex the
server exec jar... I wonder if we can do relative links in bintray's readme.

**Comment by adriancole** [comment]
This came up again today, where @sushobhitr was trying to run maven and failed. I think it is important to remove running maven as the quick-start and be explicit about downloading the jar because it will lead to less time explaining things. Few zipkin users should need to run maven, as it should be a functional server that doesn't need to be modified in order to run.

**Comment by abesto** [comment]
We can get the latest version with `https://api.bintray.com/packages/openzipkin/maven/zipkin-java/versions/_latest | jq '.name' -r`, but people won't generally have `jq`, so we can fall back to `sed`:

```
curl https://api.bintray.com/packages/openzipkin/maven/zipkin-java/versions/_latest | sed 's/.*”name" *: *"\([^"]*\)".*/\1/‘
```

This is a somewhat robust way of parsing the version number out of the response JSON. It can then be substituted into the URL, and the whole thing can be wrapped into a script (think `curl http://zipkin.io/get.sh | sh`).

For Windows support, we can either do the same in powershell, or switch to something we know all users will have - we _could_ implement this in Java, do the JSON parsing correctly in there. We'd then have something like this in `zipkin.io/get.sh`:

```
wget http://zipkin.io/get.jar
java -jar get.jar
rm get.jar
```

**Comment by abesto** [comment]
Downside to this approach: it's not clear from the README what is happening. Is this installing things on my computer? Should I be in some "toy" folder first?

**Comment by adriancole** [comment]
I think the curl-sh thing is a pretty good way to address this.

**Comment by eirslett** [comment]
Another option is to build debian/yum/homebrew packages.

**Comment by adriancole** [comment]
I think if we had a windows option, then we could forgo the curl version
completely?

**Comment by abesto** [comment]
@eirslett Debian / Yum packages bring a whole lot of baggage - specifically, distro-specific configurability of (common?) options, as well as integrating with whatever init system is in vogue this week. In the long term I'd love that, but it feels like a cannon-sparrow situation (does this exist in English? "shooting a sparrow with a cannon"?). Homebrew, yeah, I can see that work; generally I wouldn't expect homebrew to be a package manager where Zipkin is used in production, so it plays well with the "quick-start" story.

@adriancole I don't get that, sorry. Care to elaborate?

**Comment by adriancole** [comment]
I meant that when there's been questions on getting started, often they are
on Windows.

I don't know if there's an easy packaging option like homebrew for Windows,
but if there isn't, We'd probably still need some manual download
instructions for folks in that camp.

**Comment by adriancole** [comment]
The more I think about it, the more I wonder if we can't just auto-update a
download version link in the README on release.. It would make this very
simple. Click here and java -jar the result, right?

Package managers could be added, still, but this might be low effort and
not sensitive to getting started people's environment.

Thoughts?

**Comment by abesto** [comment]
Sure, we can; it's as easy as a `sed` plus a `git commit` (plus making sure `git push` will run with the right credentials). I have some misgivings about how to do this in a way that's robust enough; if we change the wording in the README around the version, will we remember to update this script? My best way for avoiding this is adding a human into the process, which defeats the whole purpose.

**Comment by eirslett** [comment]
[Chocolatey](https://chocolatey.org/) is homebrew for Windows, but it's not widely used.

If we can add custom javascript to zipkin.io, we could use it to make an AJAX call to bintray to fetch the latest release, and then build the URL from that.

**Comment by abesto** [comment]
Hm, we could add a custom variable to the source of zipkin.io and interpolate that into the contents at build time with Jekyll. That variable could very reliably be bumped by a script as part of the automated release process.

**Comment by eirslett** [comment]
The issue then is that we have to re-publish zipkin.io for every release, is that right?

**Comment by adriancole** [comment]
I'd like to agree that package management is helpful but we have to admit
that without Windows support it doesn't solve this issue I opened.

I reported this issue because a couple people struggled to run a build
tool. At least one of the two was running Windows. Reports like this also
happened often in the old project, like gradle hanging or questions about
98% done etc. We need to solve the front door experience and ack that
Windows was an OS in this. The less OS environment we need to rely on, the
better.

Download this link + java won't make this without questions, but it will
definitely help in case someone doesn't have a normal version of sed etc.

This issue was opened for quick start, not the general issue of package
management. A human is always involved in quick start! I really like
package management, just don't want to lose track of this issue in the
process. I'm also a bit concerned about making packages for OS unless we
can test them. Ex I don't run Windows.. I'd like to discuss this sort of
package related thing in an issue that isn't this issue, as while
interesting, it is easy to get lost in the weeds. The road I am suggesting
is to fork the package management and the OS diversity that includes to a
separate issue. Until that's solved for Windows if can't obviate this one,
and this one would be a shame to not solve now.

----

Maven prepare task already updates text files, so it might already support
this. Let's say the manual download link broke eventually. That would suck
but in the mean time it would be easier to fix than have to walk someone
through a process of figuring out which jar is the right one etc. That is
an unnecessary experience failure and ties folks like me up with
undifferentiated work, hence this issue.

If we had the JavaScript route, then the dynamic content would make it not
dependent on a build step, or a tool Windows might not have. so that's more
ideal in my book. I like it, but wonder if markdown can embed this, or if
we'd move the quick start to zipkin.io and link out (maybe that's best)?

**Comment by eirslett** [comment]
A KISS solution would be to present direct download URLs to the "latest-ish" released shadow-jar (unless it's too far behind, it shouldn't matter) and then provide instructions on how to find the latest version ("replace xxx with yyy in the url")

We wouldn't need to update the download URL for every release, but could do it once every full moon.

**Comment by abesto** [comment]
@eirslett Releasing zipkin.io takes a single `git push`, so I feel OK about the overhead there. Easy to automate too.

**Comment by adriancole** [comment]
Here's a gitter transcript about how-to on windows that occurred again just now on gitter. Seems downloading a link worked out pretty well.

```
Bartosz Sypytkowski @Horusiath 20:19
Hi all. I have a question regarding installing zipkin on windows - is there any tutorial about this? I have a heavy problem finding any complete docs about installation, and any windows-oriented hints are basically non-existent in that matter.

Adrian Cole @adriancole 20:36
@maihacke the migration off the scala project is on the way towards done per openzipkin/zipkin#1071
functionally, everything that exists in the former exists in the latter, and there are some running zipkin-java in production. The logging is better, metrics are more sane, there are benchmarks etc
however zipkin-java isn't 1.0 and as deployed as the old code, so it will probably be a month or two more before we cut over
@Horusiath are you looking to try it on windows or run it as a server on windows?

Bartosz Sypytkowski @Horusiath 20:40
@adriancole if I don't want to spawn VM on windows, those two statements are pretty much the same  But in general I need a zipkin example server, which I could use to test my services during development

Adrian Cole @adriancole 20:41
ok so I guess the question is more about if you are planning to run this localhost like etc

Bartosz Sypytkowski @Horusiath 20:41
yes

Adrian Cole @adriancole 20:41
ok for now, the quick start on windows isn't incredible, but we're trying to sort that out
you can tag this, as well openzipkin/zipkin-java#198
since it isn't incredible, I'll tell you what to do 
first, do you have a JRE installed?
ex java works somehow?

Bartosz Sypytkowski @Horusiath 20:43
I have both java and scala on board

Adrian Cole @adriancole 20:44
ok the latest version of zipkin-java is 0.18.2, which is sortof hard to see, but listed on the readme
we will make this link easy to get, but in the mean time, .. just download it https://jcenter.bintray.com/io/zipkin/java/zipkin-server/0.18.2/zipkin-server-0.18.2-exec.jar

Bartosz Sypytkowski @Horusiath 20:44
 The requested path was not found.

Adrian Cole @adriancole 20:44
weird. a colon snuck in there
corrected

Bartosz Sypytkowski @Horusiath 20:44
nvm, I got it

Adrian Cole @adriancole 20:45
if you "java -jar " that file, it should start with an in-memory server, listening on 9411
the endpoints etc are documented here. there's a bias towards environment variables https://github.com/openzipkin/zipkin-java/tree/master/zipkin-server#endpoints
probably, the first thing you'd do is just open http://localhost:9411 and click around

Bartosz Sypytkowski @Horusiath 20:47
do I need to have some prerequisites here? like zookeeper server running or something like that?

Adrian Cole @adriancole 20:47
because zipkin is self-tracing, it will generate data
there's no required dependency except java
things like mysql, cassandra, etc are opt-in
so if you just start it, it won't persist any data, rather hold it in memory

Bartosz Sypytkowski @Horusiath 20:52
it's working. Thanks! 
```

**Comment by abesto** [comment]
Alright, I'll try to summarize.

## Requirements

As I see them. Not all of these have been +1'd by others.

 * Getting started instructions shouldn't contain the string `mvn` (should fetch the released jar instead)
 * The instructions should ideally be copy-paste-able
 * There should be no magic involved in the instructions.
 * The instructions should point to the latest released stable version
 * Updating the instructions should be a single step, ideally done by Travis
 * Instructions should be provided for both *nix and Windows

## Making a decision

Lots of options, weighing the trade-offs is probably subjective. I propose we use [Condorcet](https://en.wikipedia.org/wiki/Condorcet_method) to resolve this; please add your "ballot" (order of preference between the options) at https://www.condorcet.vote/Vote/5DE9896944/Admin/F9CEFC1482/. The page is in beta (but I didn't find a better one); click "Candidates" at the bottom, and use those names, for instance you can write `curlzipkinio>sedref>sed` as a vote. Unmentioned candidates are ranked same as the lowest-ranked candidate.

## Candidates

 * **sed README.md**: Provide copy-paste-able instructions with hard-coded versions in README.md. Cchange the relevant strings in `README.md` with a `sed` script (or some other text manipulation thingy) at the end of the release process. Fulfills all requirements, at the cost of breaking when we change the README and forgot to update the script. We can add a test that verifies the new version appears in the text of the README as many times as we expect it.

 * **reference-style link**: Include copy-paste-able instructions for some reasonably recent version, update manually now and then. Include a reference-style link (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to the latest `jar` that can be manually downloaded. Updating where the reference points is quite robust, is resilient to changes in text around the instructions. Downside: copy-paste-able instructions are sometimes out of date.

 * **reference-style link + sed README.md**: Combine the above two options. Even if the less robust part fails, the link to the latest version will still be OK.

 * **curl bintray**: Include a `curl` command (or equivalent) that calls the Bintray API to figure out the latest version in the instructions. The actual download step uses the version provided by this. Adds some magic to the instructions. Response from bintray is JSON. PowerShell v3 includes support for JSON, so we're good there, but on *nix we have sub-optimal ways to parse it:

  * **curl bintray + jq**: Use https://stedolan.github.io/jq/. Not everyone will have it, and it's a strange requirement to have.
  * **curl bintray + sed**: Parsing the JSON response with `sed` works, and is somewhat robust, but still ugly and can theoretically fail if the JSON formatting changes significantly.
  * **curl bintray + java**: Write a minimal installer in Java that fetches the latest version number, then either outputs it or downloads it as well. Adds magic, but is portable and consistent and robust (can do proper JSON parsing).

 * **curl zipkin.io**: Create a page on `zipkin.io` that contains exactly the latest released version number. Update this page from Travis (all it takes is a `cat`, a `git commit` and a `git push`). Include a `curl` command (or equivalent) that fetches the version number from this page. The actual download step uses the version provided by this. Adds some magic to the instructions.

**Comment by adriancole** [comment]
nice writeup, but I hope I never have to use that voting tool again. It is
about as inviting as staring into accidentally recursive code.

Maybe next time we have 3 people .. just ask us to vote here? It took me a
while to figure out that "Edit Vote" was the way to add a vote, and that my
name is a tag.

**Comment by abesto** [comment]
Heh. Alright, that's good feedback, it wasn't nearly as painful for me. Won't use again!

**Comment by abesto** [comment]
Oh and... the whole vote is one big `500` now. Please vote here in comments. :D

**Comment by adriancole** [comment]
I just thought of another option.. since java is needed anyway, we could have one that uses java instead of curl (as opposed to curl + java). Rationale is, if java doesn't work, the server won't.

Ex.
```
java GetZipkinServerJar (where we check-in LatestServer.class eventhough it looks bad).
java -jar zipkin-server
```

**Comment by adriancole** [comment]
ack that the downside of ^^ is that it wouldn't have a nice status bar etc.

on that note, I'm pretty much good with failsafe instructions where a user is told to download a link we supply, and isn't dependent on anything including curl to do that... so options 1, 2 or 3
