### ISSUE TITLE
Scope: query and collector? or also web?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#2]
Currently, the core pieces needed to standup zipkin are the collector, query, and web service. The web service, however, really only needs access to a query service.

Should we start scope as collector and query?

**Comment by adriancole** [comment]
@jpinner I think you've tried to make a splunk impl and needed to modify the web server.. is that right?

**Comment by b** [comment]
zipkin-web doesn't need to exist and should instead be entirely javascript in the browser calling a query endpoint.

**Comment by eirslett** [comment]
@b +1, let's make zipkin-query expose the HTTP interface that zipkin-web already exposes today (move the code from zipkin-web to zipkin-query), which can be done both in the "old" zipkin and in zipkin-java. But I guess that's a separate issue.

**Comment by spencergibb** [comment]
So just http api, not html/js/css?

**Comment by b** [comment]
something has to serve the static assets. that can either be zipkin-query or any web server, like nginx. the former is easiest for people getting started.

**Comment by adriancole** [comment]
current impl has a package for scribe and one for query. These both are hosted on "server" which can be deployed to the same targets as "collector" and "query" once were (as it listens on both ports).

there's no web at the moment.

closed via #5
