### ISSUE TITLE
@Conditional composition in zipkin-java not working as expected

### ISSUE THREAD

**Issue by dsyer** [openzipkin/zipkin-java#202]
Fortunately the workaround is easy: just use 

```
  @Conditional(ConditionalOnKafkaZookeeper.KafkaEnabledCondition.class)
  @ConditionalOnClass(name = "zipkin.kafka.KafkaCollector")
```

in place of `@ConditionalOnKafkaZookeeper`.

We had a long look at this and boiled it down to probably a bug in Spring. TL;DR: the composed condition should work, but doesn't, and you end up only evaluating one of the conditions.

**Comment by adriancole** [comment]
thanks for the tip. will fix

**Comment by dsyer** [comment]
https://jira.spring.io/browse/SPR-14257
