### ISSUE TITLE
Fix regression where making a release requires snapshot version to match release version

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#215]
In openzipkin/zipkin, openzipkin/zipkin-java etc we do not rely on a version match to apply the next version. This means that when you tag a release, that's the version it gets. Maven's release plugin doesn't require this either! In fact, if you run the release task, it takes whatever version you say as the version.

I've come to take this behavior for granted the past few years in projects in and outside zipkin. It reduces the busy-work required to make a minor release, which in turn lowers the barrier to release often. This is particularly a problem when using semantic versions on a new project. Ex. zipkin-java has had 18 minor versions, and zipkin itself has so far had 40 in major version 1!

I've strongly voiced against the action taken because I'm the one most impacted. In the last year, I've done hundreds of releases, if you collect the zipkin-scala, the docker repos, the satellites etc. As a releaser in *any* project, I'd protest against intentionally making a minor version update to require 2 manual steps (in this case updating a pom, then doing the release).

If it were the case that there was a technical difficulty, or unimplemented feature, that's cool. For example, [docker-zipkin-java's release process doesn't currently bump versions](https://github.com/openzipkin/docker-zipkin-java/issues/1), but it could. The difference here is that the release process here, we intentionally made it 2 steps!

Let's fix it.

See https://github.com/openzipkin/zipkin-java/pull/163#issuecomment-211005586 to add policy to check that snapshot

**Comment by adriancole** [comment]
Added the following to show how to increment the version:


1. **If updating the minor or major version, check to see it matches what's current**

   This repo uses semantic versions with a twist: we update minors on api-breaks until we hit 1.0. If you are releasing
   a version that doesn't agree with what's in pom.xml, the release task will fail. To avoid that, you need to update
   the version manually. For example, the following syntax would prepare the 0.89.0 release (don't forget to commit!).
   `mvn --batch-mode release:update-versions -DdevelopmentVersion=0.89.0-SNAPSHOT`

**Comment by abesto** [comment]
One step forward, one step back? :) Sure thing, I can do that.
