### ISSUE TITLE
Projects we should be skipping are getting published

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#219]
in the old process, we were running mvn prepare against all projects, to update the versions. That's intentional.

However, deploy we skipped internal projects "-pl -:benchmarks,-:interop,-:centralsync-maven-plugin". This seems to no longer be the case, as I've noticed they've been deployed to bintray.

**Comment by abesto** [comment]
Oh snap. https://github.com/openzipkin/zipkin-java/blob/master/travis/publish.sh#L109 should take care of that, but apparently `release:perform` just dumbly uploads whatever `release:prepare` has prepared, and we explicitly run `release:prepare` against all modules to bump the versions in all modules.

Will look at this; two guesses are maybe the release plugin can be told to behave well, or we can fall back to `deploy` instead of `release:perform` (but that brings its own complications, we need to be on the right commit).

**Comment by adriancole** [comment]
ps once we have things tidy, we'll probably want to top-level the central
sync plugin, as we'd need it in brave, too.

**Comment by abesto** [comment]
@adriancole do we have a reason for not referencing the version number defined in the parent pom in submodules? That'd instantly take care of this problem, as well as remove some duplication. If that's not doable, I think https://maven.apache.org/maven-release/maven-release-plugin/examples/update-versions.html should do what we need, specifically

```
mvn release:update-versions -DautoVersionSubmodules=true
```

> You will be prompted for the version number for each module of the project. If you prefer that each module version be the same as the parent POM, you can use the option autoVersionSubmodules.

**Comment by adriancole** [comment]
Any source of drift would cause tests etc to become invalid. I still don't
understand why we cannot solve this in the release script. It was working
before.

**Comment by adriancole** [comment]
The old flow release:prepare followed by deploy worked like a champ.. got
the versions right, deployed the right code, etc. Why is it that we cannot
use this? I fear the desire to use release:perform vs deploy is cutting off
ones nose to spite their face.

**Comment by adriancole** [comment]
I think the mutual goal is to have a reliable process with the least steps, or landmines for the developer. The aim is that the resulting process does more work than before.

Our old release process required a user to invoke release:prepare with the version they want. It was almost the same as this blog: http://bithacker.org/post/120996678805/publishing-artifacts-to-bintray-from-travis-ci

Ignore the double-publish glitch, we have the same step count now as before: Instead of doing "release:prepare" with the version we want, we create a tag based on the version we want.

The main advantage now is that we don't rely on the developer's environment, except maybe git.

I'd really love for us to have the advantages of the old approach (like having no manual work to skip publishing things or updating versions), with the advantage of the new approach (prepare not executing on the laptop).

It seems the only thing we need to do in order to get there is to change the following line to invoke deploy instead of perform.

```
  ./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -pl -:benchmarks,-:interop,-:centralsync-maven-plugin -Darguments="-DskipTests" release:perform
```

I'm going to take responsibility for fixing this problem. If it doesn't work, I'll ping back!

**Comment by adriancole** [comment]
trying this with tag `release-0.18.4` and will fix it, if broke

https://github.com/openzipkin/zipkin-java/commit/e983897a8f23a1220e6e2f537548e3cba516198e

**Comment by adriancole** [comment]
fixed via https://github.com/openzipkin/zipkin-java/commit/a4bf8e1c47eae314c44fac075c89797817c93876

**Comment by abesto** [comment]
If it works, I'm happy! 👍
