### ISSUE TITLE
Add cache headers to /api/v1/services and /api/v1/spans

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#229]
In the old codebase, we had logic like the following to help from pummeling the api server when people click around in the UI

```
if (services < 3) add "Cache-Control: max-age=300, must-revalidate"
```

This is because the UI calls the /api/v1/services quite a lot, but the actual values don't change often. The extra guard was to ensure those getting started are able to see traces coming in.

Besides /api/v1/services, /api/v1/spans is also called a lot.

If we add this behavior to zipkin-server, we should probably do the same for spans, as they are quite related.

**Comment by adriancole** [comment]
I'd probably name this parameter `zipkin.query.names-max-age` as both .../spans and .../services return lists of names used by the UI.

**Comment by adriancole** [comment]
@eirslett @mansu @michaelsembwever thoughts?

**Comment by mansu** [comment]
I think the implementation sounds good. The number should be configurable. I think the caching makes sense when the number is high not low. 3 sounds like too low a number to me though.

**Comment by mansu** [comment]
I think caching a result based on number of results returned sounds weird and unexpected. I think we should just have a single field called zipkin.query.names-max-age. If it's set to 0, caching is disabled. Any positive integer should enable caching for that number of seconds. I prefer we have the same functionality for services also.

**Comment by adriancole** [comment]
actually, the trick is that performance isn't always related to the response size. For example, this was added in https://github.com/openzipkin/zipkin/issues/718 because cassandra needs to hit every node in the cluster.

The number of 3 was added so that there is a zero config option for those getting started, and we've had no issues from folks asking to change that since it was introduced last year.

**Comment by mansu** [comment]
In that case, I think the zero config option should be called as such, zipkin.query.disable_caching. Setting it based on result size makes it surprising config.

**Comment by adriancole** [comment]
having to add the config `zipkin.query.disable_caching` when getting started is not zero config :)

If you start zipkin, assuming it should cache for 5 or 10 minutes, the first hit will cache no services, or maybe 1 service. The user experience would be them having to force-reload the page before their test services are visible. This experience would go against our "5 minute story" which is an important part of zipkin, and why we made the 3 thing in the first place.

I know you are surprised, but we haven't had any issues raised against this in practice in almost a year, so I'm basically going to continue that approach as I'd rather surprise you than surprise new people who don't look at the code we are discussing.

**Comment by adriancole** [comment]
I mentioned what isn't zero config w/o mentioning what is zero config:

The service threshold is a substitute for explicit configuration. The <= 3 is basically an assumption that a production environment will have more than 3 services, or at least will rarely start with zero. The flip side is that a user getting started will start with zero services. We don't want them to have to learn configuration of how to avoid caching no services for 5 minutes. The fact that neither the production, nor the new user have to specify anything to get sensible results is zero configuration.

That the `<=3 thing` resulted in no questions, issues, or requests for documentation means that it was at least somewhat effective substitute for having to manually opt-in or opt-out of caching.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-java/pull/230

**Comment by mansu** [comment]
One more idea is to disable caching by default and add a names-max-age header for 300. If caching is disabled then new users won't see an issue. If it's enabled, 5 min is a reasonable default.

**Comment by adriancole** [comment]
That still requires someone to opt-in, and if they don't think of opting
in, their performance will suffer and not everyone knows why or what to ask
for. This would further damage our brand.

I'm really not in favor of reversing last year's decision as no aspects of
this topic changed and what we had before was easy and required no support
and no configuration.

Merging
