### ISSUE TITLE
Make build work with JDK 9

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#231]
This can capture issues and resolutions to issues building with JDK 9

The below are a subset of issues found with build 9-ea+118 (ie by setting JAVA_HOME and running `./mvnw clean install`)

 - [ ] Test failure from centralsync-maven-plugin
  * I think we should move this project to top-level since brave needs it anyway
 - [ ] ExceptionInInitializerError from maven-jar-plugin 2.6

**Comment by adriancole** [comment]
Good news is that if you only compile and run tests from core, it works. This means there's no api compilation concerns in the core library (ex use of internal classes since removed etc)

Ex. `./mvnw clean test -pl :zipkin`

**Comment by shakuzen** [comment]
It looks like version 3.0 of the `maven-jar-plugin` will be compatible with JDK 9, but it is not currently released. See [MJAR-205](https://issues.apache.org/jira/browse/MJAR-205)

**Comment by adriancole** [comment]
This issue was moved to openzipkin/zipkin#1230
