### ISSUE TITLE
Query exception resulted in empty UI page

### ISSUE THREAD

**Issue by virtuald** [openzipkin/zipkin-java#243]
I did a query in the UI for `http_url==/login`, and an exception was thrown on the server, resulting in an empty page. Would be nice to see an error message of some kind on the client (it shows up in the console log). 

Here's the server stack trace:

```
java.lang.IllegalArgumentException: binary annotation value was empty
	at zipkin.internal.Util.checkArgument(Util.java:47) ~[zipkin-0.21.2.jar:na]
	at zipkin.storage.QueryRequest.<init>(QueryRequest.java:141) ~[zipkin-0.21.2.jar:na]
	at zipkin.storage.QueryRequest$Builder.build(QueryRequest.java:275) ~[zipkin-0.21.2.jar:na]
	at zipkin.server.ZipkinQueryApiV1.getTraces(ZipkinQueryApiV1.java:101) ~[zipkin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        ...
```

**Comment by adriancole** [comment]
You mean we should make a custom error for when someone accidentally puts
'=' twice?

**Comment by adriancole** [comment]
Or do you mean the api error didnt include a message at all (besides 400)?

**Comment by virtuald** [comment]
Correct, the only way that I knew there was an error was to look at the console log.

**Comment by virtuald** [comment]
Other than that, it was just a completely blank page, which isn't a very good way to indicate an error. :)

**Comment by adriancole** [comment]
Good points. Thanks for reporting!

**Comment by eirslett** [comment]
We could potentially display errors and stack traces in the UI, if we get them formatted from the server.

**Comment by virtuald** [comment]
I've got a fix for this in https://github.com/openzipkin/zipkin/pull/1125
