### ISSUE TITLE
Investigate custom context root

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#244]
https://github.com/openzipkin/docker-zipkin/issues/97 was opened about moving all zipkin things under the context root /zipkin  (directly vs via a reverse proxy).

This might be possible with OOB spring boot. If so, we could consider this. Otherwise we can close it with explanation in case the question comes up again.

**Comment by shakuzen** [comment]
Should be as simple as setting `server.contextPath` or the equivalent environment variable `SERVER_CONTEXT_PATH`

**Comment by eirslett** [comment]
It's easy on the server side, but it would be non-trivial to implement, because our UI is a single-page web app, and it assumes absolute paths.

**Comment by adriancole** [comment]
This issue was moved to openzipkin/zipkin#1229
