### ISSUE TITLE
LazyCloseable could wait on exception

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#248]
LazyCloseable (an internal class) is used for for network connections. The attempt to do something like creating a connection has a cost. It is even more expensive to try to do something like install a schema.

There was a comment on an otherwise unrelated issue that we should slow down attempts to connect to cassandra to [no more than once per second](https://github.com/openzipkin/zipkin-java/pull/240#discussion-diff-64503761).

In practice, there would only be one attempt per second if using brave because brave schedules span writes to a single thread, and that polling interval can be no shorter than one second. However, this "being saved by the bell" is something that only applies if using brave's base class, and wouldn't apply to normal collectors, which may have unbounded callers (who don't stand in a nice 1 second spaced line!).

Instead of being "saved by the bell", we could make either a global decision or a configuration option available to slow down tries.

For example, making lazy closeables try no more than once per second is a simple thing we could do, even by hard-coding at first. By hard-coding, we don't give flexibility, but we also don't have to bubble up a configuration option through the several components that would be impacted.

Thoughts?

**Comment by adriancole** [comment]
cc @eirslett @kristofa @michaelsembwever @anuraaga @shakuzen

**Comment by anuraaga** [comment]
Sorry I don't quite understand the details of the issue - title talks about an exception (what exception?) and description seems to talk about throttling connection attempts to 1/sec. 

Would throttling involve queuing incoming requests - maybe it just involves adding N retries to any given future?

Also why 1/sec? A second seems like a long time to me but does it correspond to something, maybe a Full GC cycle?

**Comment by adriancole** [comment]
sorry.. let's say you are booting up and the backend isn't available, yet. You'd get an IOException, or perhaps an IllegalStateException when the storage component is initializing.

Upon failure, the next storage request (regardless of a read or write op), would again try to initialize the component, until it succeeded. Once succeeded, that session is cached and re-used.

The concern is that a flurry of requests attempt to initialize the component, and stack up due to the synchronization barrier. As soon as one fails, the next will try again with no delay. The concern is that the repeated connection attempts could thrash the process.

I used 1 second as that was the duration chosen in the comments that led to this issue. Certainly, I've seen backoff barriers in the past as well.

**Comment by anuraaga** [comment]
Got it - IMO since we have a health endpoint that depends on the state of the connection, there shouldn't be a huge need to worry about this. Clients definitely must be checking health and as long as they do, zipkin server would be able to limit connection attempts to the backend health check interval by design.

Of course, malicious/poorly designed clients that ignore health can bypass this. I've only seen tracing in an intra-data center situation where this isn't a problem but if we accept zipkin API being directly exposed to the world (phones) it may change the safety of the health check. If this is a concern, rate limiting in the LazyClient seems fine to me, just want to make sure it's worth it.

**Comment by adriancole** [comment]
thanks for thinking this through. In this case, health check is one of the
things that call LazyClient, the actual storage components (like
AsyncSpanConsumer) do, too. So during a failed state, these could possibly
hammer the process (ex once per kafka message). Basically, the "worth it"
guard, which I totally agree should be a conscious decision, also applies
to normal use of components (not just health checks)

**Comment by anuraaga** [comment]
Ah I was only really thinking of the HTTP API, which would be guarded by the health endpoint as long as clients behave. But I guess that doesn't rely apply to somthing like Kafka collector so yeah seems to make sense to limit in the LazyClient too.

**Comment by adriancole** [comment]
OK so I'll try and get the throttling change raised today before I
disappear across the pacific. Will start with a hard-coded 1 second cache
of any exception, which can be revisited later, should it be insufficient.
Less config the better at this point.

**Comment by adriancole** [comment]
here's the fix https://github.com/openzipkin/zipkin-java/pull/251
