### ISSUE TITLE
Document retention practice for elasticsearch

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#249]
As mentioned by @yurishkuro in response to a TTL question from @devinsba, the recommended way for ES is to use index aliases, and assign unique index names every N days and drop the old indices. It is much more performant than doing TTL and compactions.

The current implementation has an `IndexNameFormatter` that's something like `${zipkin.storage.elasticsearch.index}-yyyy-MM-dd` for timestamped entries and `${zipkin.storage.elasticsearch.index}-*` for catch-alls.

We should document how this relates to those using TTLs and any practices that would be easy to employ for expiring data.

**Comment by adriancole** [comment]
@anuraaga thoughts?

**Comment by yurishkuro** [comment]
One thing I am not sure about is whether there are actually any tools in ES to auto-expire the named indices that are outside of the retention window. I believe ES does not provide that out of the box and people are implementing adhoc devops solutions for that, which is sad.

**Comment by anuraaga** [comment]
Elasticsearch has a tool called curator which makes this pretty easy. Yeah, it is a cron job somewhere so a bit of complexity but usage is really easy, you can specify a prefix of indices to delete, when they are older than n days. e.g. 

```shell
curator delete indices --prefix zipkin- --older-than 7 --time-unit days --timestring %Y-%m-%d
```

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html

I was using this initially but we acutally use the same elasticsearch for metrics as well, for which we needed a more complex custom cleanup job written in Java, so I ended up just adding the zipkin cleanup to that job as well but when this isn't the case, curator is great.

**Comment by adriancole** [comment]
This issue was moved to openzipkin/zipkin#1222
