### ISSUE TITLE
Implement MYSQL_MAX_CONNECTIONS

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#38]
Not sure how to plug this in, but we should be able to change HikariCP's max connections value with MYSQL_MAX_CONNECTIONS

https://github.com/openzipkin/zipkin/pull/789

**Comment by dsyer** [comment]
Some the configuration options are listed here: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties. Anything that is a Java Bean property of the `DataSource` can be set using `spring.datasource.*`. Probably `spring.datasource.maxActive=...` is what you want for this.

**Comment by adriancole** [comment]
I thought I tried that.. maybe it was the capital that I missed last night.
Thx!
