### ISSUE TITLE
Add server-side sampler

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#52]
In order to be compatible with zipkin-scala's collector, we need to implement sampling, particularly the following:

`COLLECTOR_SAMPLE_RATE`: Percentage of traces to retain, defaults to always sample (1.0).

This is a rate that applies when Span.debug is not true, and treats the sample rate as a percentage. Ex. .1 means retain 10%

See https://github.com/openzipkin/zipkin/blob/master/zipkin-collector-service/src/main/scala/com/twitter/zipkin/collector/sampler/AdjustableGlobalSampler.scala

**Comment by adriancole** [comment]
@dsyer thx for reminding me about this.

**Comment by adriancole** [comment]
The following is a discussion about sampling in general as there's some important things to know. The TL;DR of the server-side is that be aware that most logic lives in the tracers, and some of that lives in propagation context.

---

Ran into a cognitive glitch I thought I'd share. The short of it is that scope is important, and we need to be aware of which sampling decisions are made where.

### This is about portability with zipkin v1 implementations
If any of what I mention below is incorrect, could be added to, or isn't clear, please reply back. If you don't like zipkin v1's approach, I probably agree, but this issue isn't a great place to voice that. Channel your energy here please! [Zipkin v2](https://docs.google.com/document/d/1ixxEs9TvhiGjJObGbRSPhSna3zHdadoUTQIZ5JKgLzU/edit) and [Distributed Context Propagation](https://paper.dropbox.com/doc/Distributed-Context-Propagation-RGvlvD1NFKYmrJG9vGCES).

### Sampling is in waves

Firstly, sampling is a multiple stage decision. First decisions are made by the instrumentation, and last are made by the collector. These decisions only take into account the trace id and configuration, so are applied on the way out.

### Instrumentation sampling policy
Here's the way most instrumentation (tracers) sample. This is a decision of whether to send spans to the collector tier.

```
if (trace has debug flag set to true) { // this lives in the span data
 send to collector
} else if (trace has sampled set) { // this lives in propagation context 
 if sampled send to collector
} else if (global sample rate exists) { // optional tracer configuration
 if sample function(traceId) send to collector
} else { // punt decision aka abstain
 send to collector
}
```

Some tracers offer other policy, too. Ex. brave has policy also based on span name. The above is just the most commonly implemented approach. Anyway, there's at least 3 ways instrumentation can drop a trace.

#### Propagation of sampling decision to the next hop
One of the more interesting ways is the `sampled` propagation field. This is implemented as the http header `X-B3-Sampled` and also in [Finagle's thrift envelope](https://github.com/twitter/finagle/blob/b6ef451c9e5aceed3eb66965278bcf1e4a27ea86/finagle-thrift/src/main/thrift/tracing.thrift#L250). Unlike the debug flag, this can say drop (sampled=false), which means a child service can choose to kill a subtree of the trace from ever reaching the collector tier.

### Collector sampling policy

Once we get to the collector, there's another layer of trimming. This is implemented fairly simply.

```
if (span has debug flag set to true) { // this lives in the span data
 store
} else if (global sample rate exists) { // optional collector configuration
 if sample function(traceId) store
}
```

Usually, there's also implicit policy at both tiers of drop on error of any sort, such as queue full or the like.

### Takeaways
* Sampling policy on the instrumentation is the first line of defence, as it 
* Subject to weather, Span.debug always wins, both in instrumentation and the collector.
* Sampling in zipkin v1 applies a consistent rate function to the trace id, expressed as a percentage encoded into a float, like .1 means 10%
* Sampling has at least 2 layers! Ex. if your instrumentation sample 10% and your collectors also sample 10%, you are getting 1%ish. (ish bc debug and errors may affect this)

### Closing notes
If folks think this qualifies as documentation, suggest where is best and I'll copy/paste.

**Comment by kristofa** [comment]
@adriancole This is really helpful. Some remarks:

   * `Instrumentation sampling policy`: I think you should add the case where sampled is set to false. In that case span must not be sent to collector tier and this decision propagates to next hop as you state. This assures we either collect a full trace or non of the spans at all.
   * Sampling in zipkin-collector comes in handy when you can't dynamically change sample rate in tracers. We have used this as a quick workaround when we noticed zipkin-collector dropped spans because backend could not keep up or when backend storage was running full. Off course having an automatically adjustable sample rate or manually changeable sample rate without having to restart services (like `ZooKeeperSamplingTraceFilter` in Brave) would be advised in future.
   * The fact that brave currently uses span id instead of trace id has no specific reason and I can't see why this would make sense.

**Comment by eirslett** [comment]
> `COLLECTOR_SAMPLE_RATE`: **Updatable via POST /config/sampleRate**; Defaults to always sample (1.0)

Why is live-updating the value necessary? (versus changing the static configuration and then restarting the collector)

**Comment by adriancole** [comment]
@eirslett `COLLECTOR_SAMPLE_RATE` updates via POST was a historical feature added eventhough it was suggested no-one uses it. I'll remove it upstream https://github.com/openzipkin/zipkin/pull/327/files#r9215131

**Comment by adriancole** [comment]
Updated description to not require HTTP config
