### ISSUE TITLE
RxJava?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#6]
I started working on an implementation using Java 8 streams, but continually find myself lacking the ability to do things present in Rx.

https://github.com/ReactiveX/RxJava

RxJava is a <1MB zero dep jar. Anyone have an opinion wrt implementing components to support collection and query with RxJava?

**Comment by spencergibb** [comment]
:+1:

**Comment by NiteshKant** [comment]
:+1:

**Comment by rtyler** [comment]
:beers:

**Comment by danchia** [comment]
+1

**Comment by eirslett** [comment]
zipkin-scala was non-blocking, which perhaps gave it a performance gain. Using RxJava increases code complexity, though (especially for the casual contributor who hasen't used Rx before) so I think we should do an experiment and compare performance tests. We should weigh the extra code complexity against the increase in performance.

**Comment by adriancole** [comment]
This issue was moved to openzipkin/zipkin#1227
