### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#63]
We have users who are each needing to build docker images ad-hoc. What's the best way to set this up for publishing? Notice that the releases are related to upstream openzipkin/zipkin images, but loosely. IOTW version 0.4 and 0.5 likely run against the same zipkin-web (as zipkin-web rarely changes).

**Comment by adriancole** [comment]
@abesto ideas? I think this is an opportunity to try out a sub-repo (which actually has a use case to be not in the mono-build)

**Comment by abesto** [comment]
What kind of users are we talking about? Is it Zipkin users who want to customize their setup? If yes, what kind of customizations? (Depending on the use-case, `ONBUILD` may or may not provide an elegant solution). Or are we talking about creating docker images for projects not yet in "mainstream" Zipkin?

In either case, my initial approach would be to set up an automated build either on Quay or Docker Hub, depending on whether there's a chance we'll want to include the image later in the monolithic release process.

**Comment by adriancole** [comment]
Well main users are examples at this point ;) There are several docker
compose files in spring that can't use zipkin-java-server as easily since
it isn't published.

There's a but or chicken egg on users,  too. It would be hard to deprecated
the anorm thing if an alternative  isn't published (which this is).

I don't mind putting it in the docker-zipkin, just wondering if this might
be a good place to pilot a spun out image.

Thanks for helping  think through this.

**Comment by abesto** [comment]
"There's a but or chicken egg on users, too." I failed to parse that, please elaborate if it's important :D

How about if I set up a minimal tag-quay-sync-dockerhub build flow in a separate repo tonight? Say, `zipkin-java-docker`? Or `docker-zipkin-java`?

**Comment by abesto** [comment]
https://github.com/openzipkin/docker-zipkin-java is now a thing.

**Comment by adriancole** [comment]
>
> "There's a but or chicken egg on users, too." I failed to parse that,
> please elaborate if it's important :D
>
oh I mean that users are more inclined to use zipkin-java, if they don't
have to build it from scratch, as the latter adds more process. We
experienced this is zipkin, too, basically the act of releasing helps
adoption.
