### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-java#7]
We should publish snapshots and releases, snapshots first

cc @kristofa @abesto @jamescway

**Comment by kristofa** [comment]
@adriancole @abesto @jamescway 
Because I have experience with publishing to Sonatype I would follow [this approach](http://central.sonatype.org/pages/ossrh-guide.html). 
Or do you prefer using bintray like we did for the other artefacts?  Do we sync to Maven Central already? Do we already have a Sonatype account?

**Comment by adriancole** [comment]
@kristofa I'm fine using sonatype directly, at least as a start. You can
ask for access here (I've been using my own creds for zipkin pushes)
https://issues.sonatype.org/browse/OSSRH-16669

**Comment by kristofa** [comment]
@adriancole Good! The issue you mention is closed. If I add a comment with my user name will they still process it?

**Comment by adriancole** [comment]
They have been, so give it a try! I can also share my creds with you and/or
otherwise loan them to the process.

**Comment by kristofa** [comment]
@adriancole I'll update the issue and give it a try. No need to share creds. I can prepare a pr with `pom.xml` changes and you can test it out if I don't get access soon enough :)

**Comment by adriancole** [comment]
Awesome

**Comment by adriancole** [comment]
Maybe next step is to setup travis to auto-publish snapshots? Ex. https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/.travis.yml

**Comment by jamescway** [comment]
@adriancole @rtyler can you contact me if you have the openzipkin credentials?  Presumably there is also an email address associated with the account.

**Comment by adriancole** [comment]
I don't have an OpenZipkin account. I have only used my sonatype account in
the past.

**Comment by adriancole** [comment]
looks like @jamescway got round 1 complete! we have snapshots.

**Comment by adriancole** [comment]
ok now snapshots are going to jfrog, like our other ones: http://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/zipkin-java/0.1.0-SNAPSHOT/

**Comment by adriancole** [comment]
rationale for switching from sonatype to jfrog snapshots is that we don't want users to have confusion by requiring them to go to different artifactory instances depending on the primary language of the project.

**Comment by adriancole** [comment]
0.1.0 is out on maven central, so this is quite a milestone!

The following will now publish to bintray: `./mvnw  -s ./.settings.xml release:prepare`
* Note: bintray does the signing, so you don't need to setup GPG.

To create a docker image from bintray, we need to do this manually via `docker-compose build`

To push to maven central, we need to do the normal manual thing for now: https://bintray.com/openzipkin/maven/zipkin-java/view#central

@abesto I suspect you might be able to help tag-automate the actual release process eventhough the above steps work for me for now. If interested, ping-back!

**Comment by abesto** [comment]
Awesomeness! I'm definitely interested, and also definitely getting into the whole "you don't have time for anything before Christmas" thing. Added to my todo list, hopefully this year, but don't hold back if someone wants to work on it.

**Comment by adriancole** [comment]
closing in favor of next steps #131

**Comment by abesto** [comment]
Oops, this fell off my todo list, sorry. Happy to see there's still progress, will keep #131 in mind.
