### ISSUE TITLE
Failed to execute goal com.mycila:license-maven-plugin:2.11:check (default) on project parent: Some files do not have the expected license header -> [Help 1]

### ISSUE THREAD

**Issue by sdcuike** [openzipkin/zipkin-java#80]
When I build ,some error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.441 s
[INFO] Finished at: 2016-02-22T15:10:48+08:00
[INFO] Final Memory: 11M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.11:check (default) on project parent: Some files do not have the expected license header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

_____
I just used -Dlicense.skip=true to bypass the failure,Can I.

**Comment by adriancole** [comment]
These files are sensitive to dates from git. When you change them,
sometimes you'll need to re-run the format plugin.

Here's instructions from CONTRIBUTING.md:

If you are adding a new file it should have a header like below. This can
be automatically added by running `./mvnw
com.mycila:license-maven-plugin:format`.

**Comment by sdcuike** [comment]
Thank you
